# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Callable, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs
from ._inputs import *

__all__ = ['FileArgs', 'File']

@pulumi.input_type
class FileArgs:
    def __init__(__self__, *,
                 connection: pulumi.Input['ConnectionArgs'],
                 path: pulumi.Input[str],
                 content: Optional[pulumi.Input[str]] = None,
                 permissions: Optional[pulumi.Input[str]] = None,
                 sftp_path: Optional[pulumi.Input[str]] = None,
                 triggers: Optional[pulumi.Input[Sequence[Any]]] = None,
                 use_sudo: Optional[pulumi.Input[bool]] = None):
        """
        The set of arguments for constructing a File resource.
        :param pulumi.Input['ConnectionArgs'] connection: The parameters with which to connect to the remote host.
        :param pulumi.Input[str] path: The path for file on remote server
        :param pulumi.Input[str] content: The content of file
        :param pulumi.Input[str] permissions: Unix permissions for file
        :param pulumi.Input[str] sftp_path: sudo mode requires a external sftp server to be running on remote host
        :param pulumi.Input[Sequence[Any]] triggers: Trigger replacements on changes to this input.
        :param pulumi.Input[bool] use_sudo: if enabled then use sudo for copy command instead of direct copy
        """
        FileArgs._configure(
            lambda key, value: pulumi.set(__self__, key, value),
            connection=connection,
            path=path,
            content=content,
            permissions=permissions,
            sftp_path=sftp_path,
            triggers=triggers,
            use_sudo=use_sudo,
        )
    @staticmethod
    def _configure(
             _setter: Callable[[Any, Any], None],
             connection: Optional[pulumi.Input['ConnectionArgs']] = None,
             path: Optional[pulumi.Input[str]] = None,
             content: Optional[pulumi.Input[str]] = None,
             permissions: Optional[pulumi.Input[str]] = None,
             sftp_path: Optional[pulumi.Input[str]] = None,
             triggers: Optional[pulumi.Input[Sequence[Any]]] = None,
             use_sudo: Optional[pulumi.Input[bool]] = None,
             opts: Optional[pulumi.ResourceOptions] = None,
             **kwargs):
        if connection is None:
            raise TypeError("Missing 'connection' argument")
        if path is None:
            raise TypeError("Missing 'path' argument")
        if sftp_path is None and 'sftpPath' in kwargs:
            sftp_path = kwargs['sftpPath']
        if use_sudo is None and 'useSudo' in kwargs:
            use_sudo = kwargs['useSudo']

        _setter("connection", connection)
        _setter("path", path)
        if content is not None:
            _setter("content", content)
        if permissions is None:
            permissions = '0664'
        if permissions is not None:
            _setter("permissions", permissions)
        if sftp_path is None:
            sftp_path = '/usr/lib/ssh/sftp-server'
        if sftp_path is not None:
            _setter("sftp_path", sftp_path)
        if triggers is not None:
            _setter("triggers", triggers)
        if use_sudo is not None:
            _setter("use_sudo", use_sudo)

    @property
    @pulumi.getter
    def connection(self) -> pulumi.Input['ConnectionArgs']:
        """
        The parameters with which to connect to the remote host.
        """
        return pulumi.get(self, "connection")

    @connection.setter
    def connection(self, value: pulumi.Input['ConnectionArgs']):
        pulumi.set(self, "connection", value)

    @property
    @pulumi.getter
    def path(self) -> pulumi.Input[str]:
        """
        The path for file on remote server
        """
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[str]):
        pulumi.set(self, "path", value)

    @property
    @pulumi.getter
    def content(self) -> Optional[pulumi.Input[str]]:
        """
        The content of file
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "content", value)

    @property
    @pulumi.getter
    def permissions(self) -> Optional[pulumi.Input[str]]:
        """
        Unix permissions for file
        """
        return pulumi.get(self, "permissions")

    @permissions.setter
    def permissions(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "permissions", value)

    @property
    @pulumi.getter(name="sftpPath")
    def sftp_path(self) -> Optional[pulumi.Input[str]]:
        """
        sudo mode requires a external sftp server to be running on remote host
        """
        return pulumi.get(self, "sftp_path")

    @sftp_path.setter
    def sftp_path(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "sftp_path", value)

    @property
    @pulumi.getter
    def triggers(self) -> Optional[pulumi.Input[Sequence[Any]]]:
        """
        Trigger replacements on changes to this input.
        """
        return pulumi.get(self, "triggers")

    @triggers.setter
    def triggers(self, value: Optional[pulumi.Input[Sequence[Any]]]):
        pulumi.set(self, "triggers", value)

    @property
    @pulumi.getter(name="useSudo")
    def use_sudo(self) -> Optional[pulumi.Input[bool]]:
        """
        if enabled then use sudo for copy command instead of direct copy
        """
        return pulumi.get(self, "use_sudo")

    @use_sudo.setter
    def use_sudo(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "use_sudo", value)


class File(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 connection: Optional[pulumi.Input[pulumi.InputType['ConnectionArgs']]] = None,
                 content: Optional[pulumi.Input[str]] = None,
                 path: Optional[pulumi.Input[str]] = None,
                 permissions: Optional[pulumi.Input[str]] = None,
                 sftp_path: Optional[pulumi.Input[str]] = None,
                 triggers: Optional[pulumi.Input[Sequence[Any]]] = None,
                 use_sudo: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        """
        A file to be created on a remote host. The connection is established via ssh.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[pulumi.InputType['ConnectionArgs']] connection: The parameters with which to connect to the remote host.
        :param pulumi.Input[str] content: The content of file
        :param pulumi.Input[str] path: The path for file on remote server
        :param pulumi.Input[str] permissions: Unix permissions for file
        :param pulumi.Input[str] sftp_path: sudo mode requires a external sftp server to be running on remote host
        :param pulumi.Input[Sequence[Any]] triggers: Trigger replacements on changes to this input.
        :param pulumi.Input[bool] use_sudo: if enabled then use sudo for copy command instead of direct copy
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: FileArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A file to be created on a remote host. The connection is established via ssh.

        :param str resource_name: The name of the resource.
        :param FileArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(FileArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            kwargs = kwargs or {}
            def _setter(key, value):
                kwargs[key] = value
            FileArgs._configure(_setter, **kwargs)
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 connection: Optional[pulumi.Input[pulumi.InputType['ConnectionArgs']]] = None,
                 content: Optional[pulumi.Input[str]] = None,
                 path: Optional[pulumi.Input[str]] = None,
                 permissions: Optional[pulumi.Input[str]] = None,
                 sftp_path: Optional[pulumi.Input[str]] = None,
                 triggers: Optional[pulumi.Input[Sequence[Any]]] = None,
                 use_sudo: Optional[pulumi.Input[bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = FileArgs.__new__(FileArgs)

            connection = _utilities.configure(connection, ConnectionArgs, True)
            if connection is None and not opts.urn:
                raise TypeError("Missing required property 'connection'")
            __props__.__dict__["connection"] = None if connection is None else pulumi.Output.secret(connection)
            __props__.__dict__["content"] = content
            if path is None and not opts.urn:
                raise TypeError("Missing required property 'path'")
            __props__.__dict__["path"] = path
            if permissions is None:
                permissions = '0664'
            __props__.__dict__["permissions"] = permissions
            if sftp_path is None:
                sftp_path = '/usr/lib/ssh/sftp-server'
            __props__.__dict__["sftp_path"] = sftp_path
            __props__.__dict__["triggers"] = triggers
            __props__.__dict__["use_sudo"] = use_sudo
            __props__.__dict__["md5sum"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["connection"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(File, __self__).__init__(
            'file:remote:File',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'File':
        """
        Get an existing File resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = FileArgs.__new__(FileArgs)

        __props__.__dict__["connection"] = None
        __props__.__dict__["content"] = None
        __props__.__dict__["md5sum"] = None
        __props__.__dict__["path"] = None
        __props__.__dict__["permissions"] = None
        __props__.__dict__["sftp_path"] = None
        __props__.__dict__["triggers"] = None
        __props__.__dict__["use_sudo"] = None
        return File(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def connection(self) -> pulumi.Output['outputs.Connection']:
        """
        The parameters with which to connect to the remote host.
        """
        return pulumi.get(self, "connection")

    @property
    @pulumi.getter
    def content(self) -> pulumi.Output[Optional[str]]:
        """
        The content of file
        """
        return pulumi.get(self, "content")

    @property
    @pulumi.getter
    def md5sum(self) -> pulumi.Output[str]:
        """
        The md5sum of the uploaded file
        """
        return pulumi.get(self, "md5sum")

    @property
    @pulumi.getter
    def path(self) -> pulumi.Output[str]:
        """
        The path for file on remote server
        """
        return pulumi.get(self, "path")

    @property
    @pulumi.getter
    def permissions(self) -> pulumi.Output[Optional[str]]:
        """
        Unix permissions for file
        """
        return pulumi.get(self, "permissions")

    @property
    @pulumi.getter(name="sftpPath")
    def sftp_path(self) -> pulumi.Output[Optional[str]]:
        """
        sudo mode requires a external sftp server to be running on remote host
        """
        return pulumi.get(self, "sftp_path")

    @property
    @pulumi.getter
    def triggers(self) -> pulumi.Output[Optional[Sequence[Any]]]:
        """
        Trigger replacements on changes to this input.
        """
        return pulumi.get(self, "triggers")

    @property
    @pulumi.getter(name="useSudo")
    def use_sudo(self) -> pulumi.Output[Optional[bool]]:
        """
        if enabled then use sudo for copy command instead of direct copy
        """
        return pulumi.get(self, "use_sudo")

