// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

import * as utilities from "../utilities";

export interface ConnectionArgs {
    address?: pulumi.Input<string>;
    privateKey?: pulumi.Input<string>;
    user?: pulumi.Input<string>;
}

export interface HooksArgs {
    commandAfterCreate?: pulumi.Input<string>;
    commandAfterDestroy?: pulumi.Input<string>;
    commandAfterUpdate?: pulumi.Input<string>;
}
/**
 * hooksArgsProvideDefaults sets the appropriate defaults for HooksArgs
 */
export function hooksArgsProvideDefaults(val: HooksArgs): HooksArgs {
    return {
        ...val,
        commandAfterCreate: (val.commandAfterCreate) ?? "",
        commandAfterDestroy: (val.commandAfterDestroy) ?? "",
        commandAfterUpdate: (val.commandAfterUpdate) ?? "",
    };
}
