# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_file.remote as __remote
    remote = __remote
else:
    remote = _utilities.lazy_import('pulumi_file.remote')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "file",
  "mod": "remote",
  "fqn": "pulumi_file.remote",
  "classes": {
   "file:remote:File": "File"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "file",
  "token": "pulumi:providers:file",
  "fqn": "pulumi_file",
  "class": "Provider"
 }
]
"""
)
